### ISSUE TITLE
unable to use with prebuild for Electron 4 because of ABI incompatibilities

### ISSUE THREAD

**Issue by Akumzy** [atom/node-keytar#133] opened 2018-10-11 12:32 UTC
I just I deleted and re-install my node_modules since then I started getting this error
electron version: 4.0.0@beta.1
system: Ubuntu
`
  v8_natives_data:symbol lookup error: /home/akumzy/node_modules/keytar/build/Release/keytar.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE
`

**Comment by kaniseo** [comment] 2018-11-05 23:18
Same with: 
keytar: 4.3.0
electron: 3.0.4
node: 10.2.1
npm: 5.6.0

tested with electron-quick-start.

**Comment by janis91** [comment] 2019-01-07 14:34
Same here.

I can reproduce this error only when using keytar v4.3.0.
With v4.2.1 it is working regardless of the electron version (3 or 4). Node version 10.

Hope this helps.

**Comment by vladimiry** [comment] 2019-01-08 23:42
Facing a similar issue. Though not just with `keytar`, but with `sodium-native` too, possibly with all the native modules that go with prebuilts. I ended up for now forcing removing all the prebuilts and then triggering rebuilding from sources.

**Comment by bendemboski** [comment] 2019-01-09 06:12
I'm pretty sure I've tracked down the cause of this. It's [this](https://github.com/lgeiger/node-abi/issues/54) bug in `node-abi` that is making `prebuild` and `prebuild-install` think that the same binaries can be used for Electron 3 and Electron 4, when in reality the ABI changed between them.

**Comment by shiftkey** [comment] 2019-01-09 12:46
@bendemboski thanks for digging into this. I'll keep an eye on https://github.com/lgeiger/node-abi/pull/55.

**Comment by aabuhijleh** [comment] 2019-01-30 10:18
Is there a viable workaround? I need to user Electron v4 and cannot downgrade. Is there a way to use both keytar and Electron v4?

**Comment by shiftkey** [comment] 2019-01-31 22:58
While we're blocked on Electron getting it's own Node ABI version for the 4.x series, the [`4.3.2`](https://github.com/atom/node-keytar/releases/tag/v4.3.2) release has a workaround that ensures `prebuild-install` is not attempted for Electron 4.x builds.

Please try it out and see if this makes your lives easier.

**Comment by shiftkey** [comment] 2019-02-02 01:12
The Electron team just opened https://github.com/electron/electron/pull/16687 which will change the ABI version for the 4.0.x series to 69 (rather than 64). Once that makes it into a stable release we can refine the patch in #154 to only catch matches to the old (incorrect) ABI version.

**Comment by shiftkey** [comment] 2019-02-05 13:06
This has taken a while for all the upstream pieces to be resolved, but the two last PRs I've opened today should close this out:

 - #156 - if you are trying to `prebuild` against a `4.x` version before `4.0.4`, you will see an error pointing you to the `node-abi` discussion
 - #157 - the next update to `keytar` will build for the newest Electron ABI so the `prebuild-install` behaviour is restored

Upgrading to the latest `4.x` release should get you back to a happy place once those are released.

**Closed** 2019-02-05 17:33 UTC
Labels: bug

**Comment by adeperio** [comment] 2019-02-19 01:46
Looking forward to that release @shiftkey any idea when it may be online?

**Comment by adeperio** [comment] 2019-02-19 01:54
Hi @shiftkey looking forward to the new keytar prebuilds. Currently I am unable to build a windows build on mac with electron 4.0.4 and I suspect a new update to the keytar prebuilds might help

**Comment by bendemboski** [comment] 2019-02-19 02:55
@adeperio the [v4.4.0](https://github.com/atom/node-keytar/releases/tag/v4.4.0) release has the latest `prebuild-install` and `electron-v69` binaries, and should work fine for you with electron >= 4.0.4 -- I'm using it with 4.0.4 and it's working fine for me.

**Comment by BitForger** [comment] 2019-04-24 15:53
Experiencing this issue with keytar@4.5.0 node@10.11 electron@4.1.4. It's been the reported error or 
```
Error: The module '/Users/yungdev/Projects/formed-util/node_modules/keytar/build/Release/keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
```
When I rebuild like directed in posts it results in the error thrown in #134 and I causes the app to crash. Suggestions?

**Comment by BitForger** [comment] 2019-04-24 16:10
> Experiencing this issue with keytar@4.5.0 node@10.11 electron@4.1.4. It's been the reported error or
> 
> ```
> Error: The module '<path-to-project>/node_modules/keytar/build/Release/keytar.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 69. This version of Node.js requires
> NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
> ```
> When I rebuild like directed in posts it results in the error thrown in #134 and I causes the app to crash. Suggestions?

Resolved this by following the steps in https://github.com/atom/node-keytar/issues/134#issuecomment-430766628 and rolling electron version back to `^4.0.0`
