### ISSUE TITLE
keytar.node reported ass Win32/Trojan?

### ISSUE THREAD

**Issue by HighTide1** [atom/node-keytar#78] opened 2017-09-27 22:47 UTC
Hello everyone. I've just recently tried to get atom-windows,zip to extract and install successfully, but I keep getting Windows Defender detecting keytar.node as a trojan, along with several other antivirus scanners (to see an example, upload keytar.node to VirusTotal). As I got atom-windows.zip directly from the GitHub release, either I'm getting a false positive, or there's a second CCleaner going on here. Should I just report this to Microsoft (and several antivirus vendors) as a false positive? Or can someone else confirm this?

**Comment by dweremeichik** [comment] 2017-09-27 23:14
Duplicate of #75

**Comment by HighTide1** [comment] 2017-09-27 23:24
I saw #75 when I was looking. Is there any way I can really be sure, though? If only Windows Defender reported it, I would think it a false positive, but I've gotten several different antivirus software to report it as a Trojan, Ransomware, and all sorts of other bad-things. I also sort of need to prove to a friend that I didn't infect their machine the first time I used it.

**Closed** 2017-09-27 23:24 UTC

**Comment by 50Wliu** [comment] 2017-09-27 23:30
@HighTide1 Atom's Windows releases come directly from AppVeyor, so if you wanted to, you could try downloading `atom-windows.zip` directly from the artifacts page: https://ci.appveyor.com/project/Atom/atom/build/8296/job/3xpxa8h2foy92m9f/artifacts (that one is on the 1.20-releases branch, so it should be pretty stable).  And since Atom's build scripts (as well as keytar!) are all open-source, you can verify that nothing suspicious is going on behind the scenes.
