### ISSUE TITLE
Using libsecret causes headless builds to fail (Use pass instead?)

### ISSUE THREAD

**Issue by cullub** [atom/node-keytar#292] opened 2020-07-27 16:07 UTC
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I'm using node-keytar in a headless linux build.  However, libsecret (the secretservice library) doesn't support headless builds:

```
Error: Cannot autolaunch D-Bus without X11 $DISPLAY
```

### Steps to Reproduce

1. Create a docker image `FROM node:14.4.0-slim` and `RUN apt-get install libsecret-1-dev -y`, and `RUN npm install keytar`.
2. run the docker image on a nodejs file that requires keytar
3. The above error appears.

**Expected behavior:**

Clean run, with no errors

**Actual behavior:**

```
Error: Cannot autolaunch D-Bus without X11 $DISPLAY
```

**Reproduces how often:**

100% of the time.

### Versions

nodejs 14.5.0

### Additional Information

X11 seems to be an internal dependency of libsecret.  Have we considered using a different library that doesn't depend on a GUI?  Needing X11 seems a bit hacky.

**Comment by shiftkey** [comment] 2020-07-27 16:16
Closing as a duplicate of #224 - there are some workarounds in there but I cannot recommend them because it's been a while since I last looked into that area.

**Closed by shiftkey** 2020-07-27 16:16 UTC
