### ISSUE TITLE
Node-keytar should support kde-wallet on linux

### ISSUE THREAD

**Issue by belldandu** [atom/node-keytar#44] opened 2016-07-05 20:47 UTC
libgnome-keyring conflicts with Kwallet

https://github.com/brave/browser-laptop/issues/1536

**Comment by mnquintana** [comment] 2016-07-05 21:00
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/node-keytar/issues/17 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-07-05 21:00 UTC
